insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Kati', 'Rickett', 'krickett0', '1996-01-17', 'F', 'krickett0@ted.com', 'nP2!oV2f');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Irina', 'Coales', 'icoales1', '2022-05-11', 'F', 'icoales1@g.co', 'vX1"qh=zBrq');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Vladimir', 'Hover', 'vhover2', '2004-01-30', 'M', 'vhover2@geocities.com', 'lL7`aBvE#&(+');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Free', 'Barnwill', 'fbarnwill3', '2002-06-25', 'M', 'fbarnwill3@japanpost.jp', 'aJ7\Kk2T7>OwO.s');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Rafa', 'Balcombe', 'rbalcombe4', '2014-01-13', 'F', 'rbalcombe4@ft.com', 'mE3*`\!72~');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Aubrey', 'Blackett', 'ablackett5', '2023-02-14', 'M', 'ablackett5@hubpages.com', 'rD8''/|F6e');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Allison', 'Eggar', 'aeggar6', '2009-04-08', 'F', 'aeggar6@angelfire.com', 'lG9<}8*9');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Aloysius', 'Vowells', 'avowells7', '2015-07-16', 'M', 'avowells7@addtoany.com', 'xA3,=4(#');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Lon', 'Corbie', 'lcorbie8', '2004-12-26', 'M', 'lcorbie8@de.vu', 'iI6''+($Q');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Gardner', 'Le Guin', 'gleguin9', '2023-05-27', 'M', 'gleguin9@wikispaces.com', 'sD5&n+B8,L)W6lM');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Eddy', 'Yegorev', 'eyegoreva', '2000-04-01', 'F', 'eyegoreva@gmpg.org', 'qY4!`1tw(QA49GT');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Hill', 'Riccardelli', 'hriccardellib', '2014-08-10', 'M', 'hriccardellib@weebly.com', 'aT8!Hoh/ptV_C');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Vivyan', 'Osgardby', 'vosgardbyc', '2004-09-28', 'F', 'vosgardbyc@cnet.com', 'aX9?|U4QQ2');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Bren', 'McKeating', 'bmckeatingd', '2005-11-14', 'M', 'bmckeatingd@wired.com', 'kV7*(kj{C>b3n_?');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Dudley', 'Lethby', 'dlethbye', '2011-03-22', 'M', 'dlethbye@yellowpages.com', 'tJ0=S%%Zu');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Wally', 'Rayworth', 'wrayworthf', '2020-03-04', 'M', 'wrayworthf@cornell.edu', 'aL6''?*sKN4P+m8)');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Alley', 'Pitkaithly', 'apitkaithlyg', '1994-08-08', 'M', 'apitkaithlyg@is.gd', 'wL9%o)O9=&5');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Violetta', 'Crus', 'vcrush', '2014-10-10', 'F', 'vcrush@mediafire.com', 'pF5*UF>nMN&uj1D_');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Angelika', 'Sumers', 'asumersi', '2011-08-07', 'F', 'asumersi@umich.edu', 'hA4=3uVau\B');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Claudette', 'Smalls', 'csmallsj', '2003-07-09', 'F', 'csmallsj@salon.com', 'hQ9@{$%Z/F');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Franny', 'Danielian', 'fdanieliank', '2008-04-08', 'M', 'fdanieliank@ucsd.edu', 'wB0%#ae~`3');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Lamond', 'Blowen', 'lblowenl', '2003-07-07', 'M', 'lblowenl@qq.com', 'kU8>&A`1u1`t$');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Leslie', 'Kanter', 'lkanterm', '1997-09-14', 'M', 'lkanterm@jugem.jp', 'cU2~XdUgS||');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Blondell', 'Hrynczyk', 'bhrynczykn', '2007-07-02', 'F', 'bhrynczykn@marketwatch.com', 'wW8''aIM0w');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Bernita', 'Kerins', 'bkerinso', '2004-10-07', 'F', 'bkerinso@scribd.com', 'pX8+zg"hG|G~.du1');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Berte', 'Potten', 'bpottenp', '2011-06-12', 'F', 'bpottenp@google.it', 'lE7*G?.H');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Raff', 'Gaskall', 'rgaskallq', '1995-07-10', 'M', 'rgaskallq@sphinn.com', 'uG2,Zf)K?c,Fx');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Prent', 'Burress', 'pburressr', '2015-03-25', 'M', 'pburressr@walmart.com', 'tQ7.i=lz8eLE');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Silvana', 'Dring', 'sdrings', '2012-10-12', 'F', 'sdrings@hhs.gov', 'pD5)pLAP&''N,kLg');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Terrance', 'Schustl', 'tschustlt', '2016-06-22', 'M', 'tschustlt@cargocollective.com', 'aS1}K7+QTB`');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Osmond', 'Furmonger', 'ofurmongeru', '2002-08-14', 'M', 'ofurmongeru@ezinearticles.com', 'eW1#Woo+6U?{T$');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Stephanus', 'Allridge', 'sallridgev', '2022-12-30', 'M', 'sallridgev@techcrunch.com', 'eE9(r@oR2D');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Cully', 'Ruberti', 'crubertiw', '2020-10-23', 'M', 'crubertiw@ftc.gov', 'mO8|)l''Gxim+na');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Rebekah', 'Wynes', 'rwynesx', '2016-01-29', 'F', 'rwynesx@clickbank.net', 'sX3@Ne64CT');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Siusan', 'Flint', 'sflinty', '1999-01-23', 'F', 'sflinty@nationalgeographic.com', 'fX2}N1k{$Cu$s+>');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Frank', 'Zanolli', 'fzanolliz', '2011-04-10', 'M', 'fzanolliz@dropbox.com', 'tF5<I+n)/`RHv');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Rogerio', 'Cuberley', 'rcuberley10', '1992-02-15', 'M', 'rcuberley10@about.com', 'aB6=$j8C*(ejw');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Myranda', 'Fipp', 'mfipp11', '2019-11-20', 'F', 'mfipp11@ehow.com', 'nB8{$>yHq"Mo');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Eadith', 'Ozanne', 'eozanne12', '1992-07-08', 'F', 'eozanne12@tinyurl.com', 'wF5\$GqOa+SJg');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Salomone', 'Schroter', 'sschroter13', '2023-01-05', 'M', 'sschroter13@bloglines.com', 'zF1_aBpm\\t%c');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Burtie', 'Gravenall', 'bgravenall14', '2010-05-19', 'M', 'bgravenall14@dot.gov', 'uB0*#w4mT?zAw3');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Brittni', 'Aymer', 'baymer15', '2021-06-16', 'F', 'baymer15@spotify.com', 'vR6.B<8wv');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Doretta', 'Enoksson', 'denoksson16', '2014-03-08', 'F', 'denoksson16@discovery.com', 'wW9(Vr~VTnCsa$');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Ronnica', 'Gerrad', 'rgerrad17', '2008-11-08', 'F', 'rgerrad17@bandcamp.com', 'mO6.Zvk(Am\');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Amelita', 'Scotchbrook', 'ascotchbrook18', '1993-10-08', 'F', 'ascotchbrook18@wordpress.org', 'rL6$$Jgh1');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Tynan', 'Maddra', 'tmaddra19', '2002-05-28', 'M', 'tmaddra19@harvard.edu', 'rD2`L!+bJNmH@p!');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Quill', 'Ivashechkin', 'qivashechkin1a', '2006-06-07', 'M', 'qivashechkin1a@nyu.edu', 'jA6)ux)G*4w');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Guilbert', 'Klemensiewicz', 'gklemensiewicz1b', '2006-12-22', 'M', 'gklemensiewicz1b@cocolog-nifty.com', 'rR7%$gvl81lQkfi');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Nick', 'Cluitt', 'ncluitt1c', '2000-03-28', 'M', 'ncluitt1c@vistaprint.com', 'rN9$.j1+vXu&,');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Abie', 'Reide', 'areide1d', '2004-04-15', 'M', 'areide1d@dyndns.org', 'xC0%PngL');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Davis', 'Izakovitz', 'dizakovitz1e', '2007-02-09', 'M', 'dizakovitz1e@sogou.com', 'nP0!!Qwm"iEfm');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Giavani', 'Walczak', 'gwalczak1f', '2021-01-12', 'M', 'gwalczak1f@eepurl.com', 'cB3.b>{7w_8ERGMV');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Jaquelyn', 'Clemencon', 'jclemencon1g', '1992-06-05', 'F', 'jclemencon1g@unicef.org', 'yY3((ro/bj(xmA');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Sandie', 'Getten', 'sgetten1h', '2000-03-24', 'F', 'sgetten1h@mozilla.org', 'pD8@iRNgkl01f');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Jane', 'Owers', 'jowers1i', '2011-01-29', 'F', 'jowers1i@mtv.com', 'xF2%x?G#_');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Wade', 'Leedal', 'wleedal1j', '2013-03-26', 'M', 'wleedal1j@php.net', 'mA1|wvsb');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Flossie', 'Hydes', 'fhydes1k', '1992-04-02', 'F', 'fhydes1k@wsj.com', 'rA4!B=(\O~F');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Yettie', 'Tibols', 'ytibols1l', '2005-10-01', 'F', 'ytibols1l@mac.com', 'zU8=dnDBmsQy');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Aron', 'Spir', 'aspir1m', '2010-08-04', 'M', 'aspir1m@who.int', 'zU4\.{(*EDR');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Liliane', 'Wakelam', 'lwakelam1n', '1994-05-04', 'F', 'lwakelam1n@goo.gl', 'qN4%!3LwY');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Nev', 'Batch', 'nbatch1o', '2014-02-01', 'M', 'nbatch1o@nationalgeographic.com', 'gC1%C}`uKmM');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Ambrosio', 'Van Hault', 'avanhault1p', '2015-03-26', 'M', 'avanhault1p@nytimes.com', 'tZ4*yR.R=S%0gS');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Ailis', 'Bartrum', 'abartrum1q', '2022-08-24', 'F', 'abartrum1q@yahoo.co.jp', 'rT9%1Zo3');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Dottie', 'McMarquis', 'dmcmarquis1r', '2005-12-24', 'F', 'dmcmarquis1r@admin.ch', 'rX1<2@Trgw{r)5');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Beverley', 'Gorrie', 'bgorrie1s', '2008-07-15', 'F', 'bgorrie1s@csmonitor.com', 'xC5$!vZpK@Q}gk\z');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Jules', 'Nafzger', 'jnafzger1t', '2019-12-13', 'M', 'jnafzger1t@latimes.com', 'jV7{TgL9\Ch1b,@');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Tamqrah', 'O''Lynn', 'tolynn1u', '2003-05-27', 'F', 'tolynn1u@wikispaces.com', 'dO4_lFb(U)7|FD');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Gwenette', 'Beauchop', 'gbeauchop1v', '2002-12-12', 'F', 'gbeauchop1v@blogger.com', 'jP9)y}y`%F3sH(A');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Celestine', 'Ride', 'cride1w', '2017-12-24', 'F', 'cride1w@friendfeed.com', 'cA7@z_A*50UXeFl');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Bernie', 'Byway', 'bbyway1x', '2003-06-26', 'M', 'bbyway1x@hugedomains.com', 'vV0/9bmx{xn,');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Tonie', 'Merington', 'tmerington1y', '2010-04-16', 'F', 'tmerington1y@msu.edu', 'iP6"U_lm9I0&E');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Abigael', 'Bresner', 'abresner1z', '2008-07-01', 'F', 'abresner1z@goo.ne.jp', 'nZ6''XGhXfbG9');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Cleavland', 'Dobel', 'cdobel20', '2019-09-19', 'M', 'cdobel20@wikipedia.org', 'qB4.{u/S''');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Janenna', 'Hunston', 'jhunston21', '2020-03-28', 'F', 'jhunston21@is.gd', 'yP7#dIoN/mBJ74U');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Aurora', 'Georgiev', 'ageorgiev22', '2000-10-16', 'F', 'ageorgiev22@webmd.com', 'sD5{gBVQRW}y(');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Knox', 'Rogez', 'krogez23', '1995-12-06', 'M', 'krogez23@github.io', 'dX1)/$#6=');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Ashlan', 'Dunkerton', 'adunkerton24', '2017-12-11', 'F', 'adunkerton24@prlog.org', 'cW3%`,ozYB7S1');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Sasha', 'Dennerley', 'sdennerley25', '2002-12-24', 'F', 'sdennerley25@creativecommons.org', 'oK1$M=dL}Et,i');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Dawna', 'Beagley', 'dbeagley26', '1997-01-14', 'F', 'dbeagley26@google.co.jp', 'oN1_CR{u6');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Jan', 'Lindro', 'jlindro27', '2015-07-06', 'F', 'jlindro27@admin.ch', 'oE7#?XJ@\`D1');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Douglas', 'Premble', 'dpremble28', '2017-09-17', 'M', 'dpremble28@clickbank.net', 'hW1=MoqPZ?lj');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Michelina', 'Torre', 'mtorre29', '1999-11-29', 'F', 'mtorre29@xing.com', 'cI8@ZJsbmzJHgO$(');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Pru', 'Lowbridge', 'plowbridge2a', '1992-04-09', 'F', 'plowbridge2a@jiathis.com', 'zO6#GsJDm4Z');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Pennie', 'Burehill', 'pburehill2b', '2000-12-17', 'M', 'pburehill2b@google.co.uk', 'wV4@6kItzQhJC"J');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Sanderson', 'Haggar', 'shaggar2c', '2013-03-18', 'M', 'shaggar2c@woothemes.com', 'xU1|}_l3');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Burr', 'Thurber', 'bthurber2d', '2004-10-02', 'M', 'bthurber2d@de.vu', 'lL2&nxj\');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Vita', 'Binny', 'vbinny2e', '2019-06-14', 'F', 'vbinny2e@apache.org', 'jD5"y`!ZL');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Pooh', 'Sackett', 'psackett2f', '2016-08-09', 'M', 'psackett2f@reference.com', 'fB0|kGH|1!iLnnT');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Marrissa', 'Biagi', 'mbiagi2g', '1994-09-28', 'F', 'mbiagi2g@engadget.com', 'uB7\SE)OTK2Zy');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Cleo', 'Guidelli', 'cguidelli2h', '2014-02-21', 'F', 'cguidelli2h@usatoday.com', 'hT7>#ySZ,Q(YAIy2');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Saxon', 'Fishbourne', 'sfishbourne2i', '2014-12-15', 'M', 'sfishbourne2i@issuu.com', 'qG6}z!TOm6U');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Gauthier', 'Bonar', 'gbonar2j', '2021-02-23', 'M', 'gbonar2j@chicagotribune.com', 'dV4,RgM3S+Tzw');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Itch', 'Bellas', 'ibellas2k', '2016-04-25', 'M', 'ibellas2k@answers.com', 'iP9_K!lIzRZ');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Noel', 'Garling', 'ngarling2l', '2005-02-14', 'F', 'ngarling2l@altervista.org', 'hI9={rm5mb');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Ivory', 'Granger', 'igranger2m', '2009-03-13', 'F', 'igranger2m@tuttocitta.it', 'nZ6{M)''vO');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Harold', 'Fearne', 'hfearne2n', '2017-10-18', 'M', 'hfearne2n@google.it', 'mX8"`V$/fY');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Fedora', 'Yaus', 'fyaus2o', '1991-10-19', 'F', 'fyaus2o@loc.gov', 'bW9/#Vqu');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Sheffy', 'Sellers', 'ssellers2p', '2022-04-05', 'M', 'ssellers2p@webs.com', 'lO5$RTKMTc$');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Dulcy', 'Tresvina', 'dtresvina2q', '2010-07-23', 'F', 'dtresvina2q@wsj.com', 'pX9"&jV@l');
insert into account (first_name, last_name, nickname, birthday, gender, email, password) values ('Judah', 'Dufaire', 'jdufaire2r', '2018-10-30', 'M', 'jdufaire2r@arstechnica.com', 'xB9}W%I*>GBuGeC');

-- mock data for post
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-06-08', '12:10', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'http://dummyimage.com/217x100.png/ff4444/ffffff', 1);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-11-12', '23:31', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 'http://dummyimage.com/125x100.png/cc0000/ffffff', 2);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-05-14', '9:54', 'Suspendisse potenti.', 'http://dummyimage.com/234x100.png/cc0000/ffffff', 3);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-05-13', '15:01', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 'http://dummyimage.com/201x100.png/dddddd/000000', 4);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-02-03', '11:22', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'http://dummyimage.com/135x100.png/cc0000/ffffff', 5);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-01-19', '20:25', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'http://dummyimage.com/187x100.png/cc0000/ffffff', 6);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-07-27', '14:41', 'Suspendisse potenti.', 'http://dummyimage.com/197x100.png/cc0000/ffffff', 7);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-10-14', '16:13', 'Phasellus sit amet erat. Nulla tempus.', 'http://dummyimage.com/240x100.png/cc0000/ffffff', 8);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-12-17', '20:56', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'http://dummyimage.com/218x100.png/ff4444/ffffff', 9);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-03-12', '18:45', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'http://dummyimage.com/160x100.png/ff4444/ffffff', 10);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-11-21', '13:02', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'http://dummyimage.com/223x100.png/cc0000/ffffff', 11);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-04-03', '6:38', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 'http://dummyimage.com/236x100.png/dddddd/000000', 12);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-11-03', '12:10', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'http://dummyimage.com/137x100.png/ff4444/ffffff', 13);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-05-25', '8:24', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'http://dummyimage.com/109x100.png/5fa2dd/ffffff', 14);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-10-13', '16:10', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'http://dummyimage.com/218x100.png/cc0000/ffffff', 15);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-04-08', '9:44', 'In hac habitasse platea dictumst.', 'http://dummyimage.com/225x100.png/5fa2dd/ffffff', 16);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-08-11', '20:00', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'http://dummyimage.com/206x100.png/ff4444/ffffff', 17);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-04-11', '9:09', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 'http://dummyimage.com/124x100.png/ff4444/ffffff', 18);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-02-14', '11:15', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'http://dummyimage.com/136x100.png/cc0000/ffffff', 19);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-04-05', '6:14', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 'http://dummyimage.com/143x100.png/cc0000/ffffff', 20);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-08-21', '22:56', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', 'http://dummyimage.com/243x100.png/5fa2dd/ffffff', 21);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-06-17', '6:15', 'Aliquam non mauris. Morbi non lectus.', 'http://dummyimage.com/239x100.png/dddddd/000000', 22);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-04-20', '21:44', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://dummyimage.com/244x100.png/ff4444/ffffff', 23);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-06-06', '13:07', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'http://dummyimage.com/239x100.png/cc0000/ffffff', 24);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2018-10-27', '20:42', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 'http://dummyimage.com/120x100.png/ff4444/ffffff', 25);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-11-13', '21:09', 'Nulla mollis molestie lorem. Quisque ut erat.', 'http://dummyimage.com/166x100.png/5fa2dd/ffffff', 26);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-01-18', '17:55', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'http://dummyimage.com/211x100.png/ff4444/ffffff', 27);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-06-03', '16:45', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'http://dummyimage.com/116x100.png/dddddd/000000', 28);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-02-01', '15:39', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'http://dummyimage.com/226x100.png/dddddd/000000', 29);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-02-27', '20:54', 'Etiam vel augue.', 'http://dummyimage.com/236x100.png/5fa2dd/ffffff', 30);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-09-30', '17:11', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'http://dummyimage.com/177x100.png/5fa2dd/ffffff', 31);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-03-21', '13:59', 'Maecenas tincidunt lacus at velit.', 'http://dummyimage.com/147x100.png/cc0000/ffffff', 32);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-04-12', '7:04', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'http://dummyimage.com/152x100.png/5fa2dd/ffffff', 33);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-09-24', '15:08', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', 'http://dummyimage.com/185x100.png/5fa2dd/ffffff', 34);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-04-30', '14:45', 'Vivamus tortor. Duis mattis egestas metus.', 'http://dummyimage.com/166x100.png/dddddd/000000', 35);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-01-28', '20:13', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'http://dummyimage.com/154x100.png/ff4444/ffffff', 36);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-07-11', '11:35', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'http://dummyimage.com/133x100.png/ff4444/ffffff', 37);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-01-28', '16:58', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'http://dummyimage.com/163x100.png/cc0000/ffffff', 38);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-05-14', '13:37', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', 'http://dummyimage.com/177x100.png/5fa2dd/ffffff', 39);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-03-16', '11:41', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 'http://dummyimage.com/233x100.png/5fa2dd/ffffff', 40);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-11-06', '18:03', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'http://dummyimage.com/146x100.png/dddddd/000000', 41);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-10-08', '15:05', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 'http://dummyimage.com/222x100.png/dddddd/000000', 42);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-09-04', '21:30', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'http://dummyimage.com/122x100.png/ff4444/ffffff', 43);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-07-29', '21:31', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'http://dummyimage.com/186x100.png/5fa2dd/ffffff', 44);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-08-21', '15:37', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', 'http://dummyimage.com/248x100.png/cc0000/ffffff', 45);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-05-20', '10:11', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'http://dummyimage.com/122x100.png/ff4444/ffffff', 46);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-02-07', '22:23', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'http://dummyimage.com/236x100.png/cc0000/ffffff', 47);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-01-07', '11:11', 'Pellentesque viverra pede ac diam.', 'http://dummyimage.com/160x100.png/cc0000/ffffff', 48);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-03-15', '6:43', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'http://dummyimage.com/220x100.png/5fa2dd/ffffff', 49);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-07-18', '18:01', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'http://dummyimage.com/107x100.png/ff4444/ffffff', 50);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-02-10', '7:14', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'http://dummyimage.com/221x100.png/cc0000/ffffff', 51);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-02-06', '7:08', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'http://dummyimage.com/197x100.png/5fa2dd/ffffff', 52);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-01-22', '23:15', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'http://dummyimage.com/205x100.png/5fa2dd/ffffff', 53);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-07-06', '15:57', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'http://dummyimage.com/224x100.png/ff4444/ffffff', 54);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-07-13', '16:46', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'http://dummyimage.com/224x100.png/dddddd/000000', 55);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-07-04', '18:11', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://dummyimage.com/241x100.png/ff4444/ffffff', 56);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-07-10', '9:04', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'http://dummyimage.com/194x100.png/cc0000/ffffff', 57);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-09-05', '12:03', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'http://dummyimage.com/187x100.png/dddddd/000000', 58);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-11-06', '8:19', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'http://dummyimage.com/218x100.png/5fa2dd/ffffff', 59);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2018-12-09', '14:28', 'Pellentesque at nulla.', 'http://dummyimage.com/105x100.png/5fa2dd/ffffff', 60);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-03-26', '14:40', 'Morbi non lectus.', 'http://dummyimage.com/201x100.png/dddddd/000000', 61);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-01-10', '12:23', 'Donec ut mauris eget massa tempor convallis.', 'http://dummyimage.com/121x100.png/dddddd/000000', 62);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-05-22', '13:56', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 'http://dummyimage.com/175x100.png/ff4444/ffffff', 63);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-06-13', '18:02', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'http://dummyimage.com/207x100.png/dddddd/000000', 64);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-02-07', '16:13', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'http://dummyimage.com/160x100.png/cc0000/ffffff', 65);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-01-14', '20:40', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 'http://dummyimage.com/203x100.png/ff4444/ffffff', 66);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-01-14', '18:30', 'Donec dapibus.', 'http://dummyimage.com/134x100.png/ff4444/ffffff', 67);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-01-16', '12:57', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', 'http://dummyimage.com/137x100.png/5fa2dd/ffffff', 68);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-10-15', '6:54', 'Suspendisse potenti.', 'http://dummyimage.com/112x100.png/dddddd/000000', 69);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-05-31', '10:03', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 'http://dummyimage.com/123x100.png/dddddd/000000', 70);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-05-28', '20:28', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 'http://dummyimage.com/128x100.png/dddddd/000000', 71);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-09-08', '7:46', 'Pellentesque viverra pede ac diam.', 'http://dummyimage.com/245x100.png/dddddd/000000', 72);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-08-28', '18:11', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'http://dummyimage.com/250x100.png/cc0000/ffffff', 73);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-07-04', '14:15', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'http://dummyimage.com/233x100.png/dddddd/000000', 74);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-08-11', '11:34', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 'http://dummyimage.com/179x100.png/cc0000/ffffff', 75);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-09-21', '22:54', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'http://dummyimage.com/193x100.png/dddddd/000000', 76);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-09-22', '17:12', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 'http://dummyimage.com/182x100.png/5fa2dd/ffffff', 77);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-10-29', '22:50', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 'http://dummyimage.com/170x100.png/ff4444/ffffff', 78);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2018-12-04', '23:16', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 'http://dummyimage.com/108x100.png/cc0000/ffffff', 79);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-03-30', '12:24', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 'http://dummyimage.com/124x100.png/5fa2dd/ffffff', 80);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-03-03', '14:31', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'http://dummyimage.com/250x100.png/5fa2dd/ffffff', 81);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-12-17', '9:59', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'http://dummyimage.com/127x100.png/dddddd/000000', 82);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-08-24', '15:54', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 'http://dummyimage.com/119x100.png/dddddd/000000', 83);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-10-04', '13:55', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'http://dummyimage.com/208x100.png/cc0000/ffffff', 84);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-06-04', '17:35', 'Nulla tellus.', 'http://dummyimage.com/146x100.png/dddddd/000000', 85);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-05-27', '11:56', 'Nunc purus. Phasellus in felis.', 'http://dummyimage.com/194x100.png/dddddd/000000', 86);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2018-12-25', '17:54', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'http://dummyimage.com/220x100.png/cc0000/ffffff', 87);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-07-25', '11:04', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'http://dummyimage.com/114x100.png/dddddd/000000', 88);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-04-26', '23:13', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'http://dummyimage.com/137x100.png/ff4444/ffffff', 89);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-03-08', '22:59', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'http://dummyimage.com/145x100.png/ff4444/ffffff', 90);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-12-27', '12:26', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'http://dummyimage.com/123x100.png/5fa2dd/ffffff', 91);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-09-14', '13:48', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', 'http://dummyimage.com/122x100.png/cc0000/ffffff', 92);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2022-04-24', '11:40', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'http://dummyimage.com/217x100.png/cc0000/ffffff', 93);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-11-30', '15:01', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'http://dummyimage.com/136x100.png/cc0000/ffffff', 94);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2019-11-26', '23:49', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 'http://dummyimage.com/103x100.png/dddddd/000000', 95);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-09-23', '17:13', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 'http://dummyimage.com/226x100.png/ff4444/ffffff', 96);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-05-03', '20:27', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'http://dummyimage.com/232x100.png/ff4444/ffffff', 97);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2021-10-05', '12:41', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'http://dummyimage.com/117x100.png/5fa2dd/ffffff', 98);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2020-10-05', '20:18', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://dummyimage.com/166x100.png/dddddd/000000', 99);
insert into post (posting_date, posting_time, post_content, post_photo, id_account) values ('2023-04-29', '10:01', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'http://dummyimage.com/120x100.png/ff4444/ffffff', 100);

-- mock data for message
INSERT INTO message (id_account_sender, id_account_receiver, message_content) VALUES
(5, 1, 'Just wanted to say hi!'),
(3, 7, 'Have you seen the latest news?'),
(6, 8, 'Meeting at 3 PM today.'),
(9, 4, 'Check out this meme!'),
(11, 14, 'How was your vacation?'),
(15, 12, 'Did you finish the project?'),
(18, 20, 'Happy birthday!'),
(21, 22, 'Let''s catch up soon.'),
(23, 24, 'Need your help with something.'),
(26, 29, 'Remember to bring snacks tomorrow.'),
(30, 32, 'Can you attend the meeting?'),
(34, 35, 'Movie night this Friday!'),
(37, 39, 'What''s your plan for the weekend?'),
(41, 44, 'New restaurant opening downtown.'),
(46, 48, 'See you at the gym.'),
(51, 52, 'Check out this article.'),
(54, 56, 'How''s the new project going?'),
(58, 60, 'Let''s go for a hike this Sunday.'),
(63, 66, 'Any update on the presentation?');

-- react_post mock datas
INSERT INTO react_post (id_account, id_post, reaction_type, reaction_datetime) VALUES
(2, 7, 'like', '2023-08-29 10:15:00'),
(5, 12, 'love', '2023-08-29 11:30:00'),
(3, 35, 'haha', '2023-08-29 12:45:00'),
(6, 50, 'who cares?', '2023-08-29 13:00:00'),
(9, 75, 'angry', '2023-08-29 14:20:00'),
(11, 22, 'like', '2023-08-29 15:45:00'),
(15, 40, 'love', '2023-08-29 16:10:00'),
(18, 60, 'haha', '2023-08-29 17:30:00'),
(21, 82, 'who cares?', '2023-08-29 18:15:00'),
(23, 5, 'angry', '2023-08-29 19:00:00'),
(26, 18, 'like', '2023-08-29 20:30:00'),
(30, 42, 'love', '2023-08-29 21:05:00'),
(34, 77, 'haha', '2023-08-29 22:40:00'),
(37, 92, 'who cares?', '2023-08-29 23:20:00'),
(41, 14, 'angry', '2023-08-30 00:10:00'),
(46, 28, 'like', '2023-08-30 01:25:00'),
(51, 55, 'love', '2023-08-30 02:15:00'),
(54, 66, 'haha', '2023-08-30 03:30:00'),
(58, 88, 'who cares?', '2023-08-30 04:00:00'),
(63, 99, 'angry', '2023-08-30 05:45:00');
